name = "drive-s3-gateway"
main = "src/worker.ts"
compatibility_date = "2024-04-01"

kv_namespaces = [
  { binding = "AUTH_KV", id = "7cf686180e5f47419597622244eaa43f" },
  { binding = "FOLDER_CACHE", id = "2f90576c89c3487f96ef2937790a5ff9" },
  { binding = "MULTIPART_UPLOADS", id = "be2a5ab9aca2462889d2299f34b8c470" }
]

[vars]
REGION = "auto"
